/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface CodeBlock {
    'code': string;
    'language': string;
    'options': any;
  }
  interface CodeBlockAttributes extends StencilHTMLAttributes {
    'code'?: string;
    'language'?: string;
    'options'?: any;
  }

  interface ComponentIndex {}
  interface ComponentIndexAttributes extends StencilHTMLAttributes {}

  interface ComponentPage {
    'match': MatchResults;
  }
  interface ComponentPageAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface CssVarSandbox {
    'code': string;
    'vars': string;
  }
  interface CssVarSandboxAttributes extends StencilHTMLAttributes {
    'code'?: string;
    'vars'?: string;
  }

  interface DocContent {
    'name': string;
    'type': 'components' | 'pages';
  }
  interface DocContentAttributes extends StencilHTMLAttributes {
    'name'?: string;
    'type'?: 'components' | 'pages';
  }

  interface DocsMenu {}
  interface DocsMenuAttributes extends StencilHTMLAttributes {}

  interface DocsPage {
    'match': MatchResults;
  }
  interface DocsPageAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'CodeBlock': Components.CodeBlock;
    'ComponentIndex': Components.ComponentIndex;
    'ComponentPage': Components.ComponentPage;
    'CssVarSandbox': Components.CssVarSandbox;
    'DocContent': Components.DocContent;
    'DocsMenu': Components.DocsMenu;
    'DocsPage': Components.DocsPage;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'code-block': Components.CodeBlockAttributes;
    'component-index': Components.ComponentIndexAttributes;
    'component-page': Components.ComponentPageAttributes;
    'css-var-sandbox': Components.CssVarSandboxAttributes;
    'doc-content': Components.DocContentAttributes;
    'docs-menu': Components.DocsMenuAttributes;
    'docs-page': Components.DocsPageAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLCodeBlockElement extends Components.CodeBlock, HTMLStencilElement {}
  var HTMLCodeBlockElement: {
    prototype: HTMLCodeBlockElement;
    new (): HTMLCodeBlockElement;
  };

  interface HTMLComponentIndexElement extends Components.ComponentIndex, HTMLStencilElement {}
  var HTMLComponentIndexElement: {
    prototype: HTMLComponentIndexElement;
    new (): HTMLComponentIndexElement;
  };

  interface HTMLComponentPageElement extends Components.ComponentPage, HTMLStencilElement {}
  var HTMLComponentPageElement: {
    prototype: HTMLComponentPageElement;
    new (): HTMLComponentPageElement;
  };

  interface HTMLCssVarSandboxElement extends Components.CssVarSandbox, HTMLStencilElement {}
  var HTMLCssVarSandboxElement: {
    prototype: HTMLCssVarSandboxElement;
    new (): HTMLCssVarSandboxElement;
  };

  interface HTMLDocContentElement extends Components.DocContent, HTMLStencilElement {}
  var HTMLDocContentElement: {
    prototype: HTMLDocContentElement;
    new (): HTMLDocContentElement;
  };

  interface HTMLDocsMenuElement extends Components.DocsMenu, HTMLStencilElement {}
  var HTMLDocsMenuElement: {
    prototype: HTMLDocsMenuElement;
    new (): HTMLDocsMenuElement;
  };

  interface HTMLDocsPageElement extends Components.DocsPage, HTMLStencilElement {}
  var HTMLDocsPageElement: {
    prototype: HTMLDocsPageElement;
    new (): HTMLDocsPageElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'code-block': HTMLCodeBlockElement
    'component-index': HTMLComponentIndexElement
    'component-page': HTMLComponentPageElement
    'css-var-sandbox': HTMLCssVarSandboxElement
    'doc-content': HTMLDocContentElement
    'docs-menu': HTMLDocsMenuElement
    'docs-page': HTMLDocsPageElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'code-block': HTMLCodeBlockElement;
    'component-index': HTMLComponentIndexElement;
    'component-page': HTMLComponentPageElement;
    'css-var-sandbox': HTMLCssVarSandboxElement;
    'doc-content': HTMLDocContentElement;
    'docs-menu': HTMLDocsMenuElement;
    'docs-page': HTMLDocsPageElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
