/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface ComponentContent {
    'name': string;
  }
  interface ComponentContentAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface ComponentIndex {}
  interface ComponentIndexAttributes extends StencilHTMLAttributes {}

  interface ComponentPage {
    'match': MatchResults;
  }
  interface ComponentPageAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface DocsMenu {}
  interface DocsMenuAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'ComponentContent': Components.ComponentContent;
    'ComponentIndex': Components.ComponentIndex;
    'ComponentPage': Components.ComponentPage;
    'DocsMenu': Components.DocsMenu;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'component-content': Components.ComponentContentAttributes;
    'component-index': Components.ComponentIndexAttributes;
    'component-page': Components.ComponentPageAttributes;
    'docs-menu': Components.DocsMenuAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLComponentContentElement extends Components.ComponentContent, HTMLStencilElement {}
  var HTMLComponentContentElement: {
    prototype: HTMLComponentContentElement;
    new (): HTMLComponentContentElement;
  };

  interface HTMLComponentIndexElement extends Components.ComponentIndex, HTMLStencilElement {}
  var HTMLComponentIndexElement: {
    prototype: HTMLComponentIndexElement;
    new (): HTMLComponentIndexElement;
  };

  interface HTMLComponentPageElement extends Components.ComponentPage, HTMLStencilElement {}
  var HTMLComponentPageElement: {
    prototype: HTMLComponentPageElement;
    new (): HTMLComponentPageElement;
  };

  interface HTMLDocsMenuElement extends Components.DocsMenu, HTMLStencilElement {}
  var HTMLDocsMenuElement: {
    prototype: HTMLDocsMenuElement;
    new (): HTMLDocsMenuElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'component-content': HTMLComponentContentElement
    'component-index': HTMLComponentIndexElement
    'component-page': HTMLComponentPageElement
    'docs-menu': HTMLDocsMenuElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'component-content': HTMLComponentContentElement;
    'component-index': HTMLComponentIndexElement;
    'component-page': HTMLComponentPageElement;
    'docs-menu': HTMLDocsMenuElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
